const codigosPaises = [
    // América
    { codigo: "CO", indicativo: "+57", nombre: "Colombia" },
    { codigo: "US", indicativo: "+1", nombre: "Estados Unidos" },
    { codigo: "MX", indicativo: "+52", nombre: "México" },
    { codigo: "AR", indicativo: "+54", nombre: "Argentina" },
    { codigo: "BR", indicativo: "+55", nombre: "Brasil" },
    { codigo: "CL", indicativo: "+56", nombre: "Chile" },
    { codigo: "PE", indicativo: "+51", nombre: "Perú" },
    { codigo: "VE", indicativo: "+58", nombre: "Venezuela" },
    { codigo: "EC", indicativo: "+593", nombre: "Ecuador" },
    { codigo: "GT", indicativo: "+502", nombre: "Guatemala" },
    { codigo: "CU", indicativo: "+53", nombre: "Cuba" },
    { codigo: "DO", indicativo: "+1", nombre: "República Dominicana" },
    { codigo: "HN", indicativo: "+504", nombre: "Honduras" },
    { codigo: "PY", indicativo: "+595", nombre: "Paraguay" },
    { codigo: "SV", indicativo: "+503", nombre: "El Salvador" },
    { codigo: "NI", indicativo: "+505", nombre: "Nicaragua" },
    { codigo: "CR", indicativo: "+506", nombre: "Costa Rica" },
    { codigo: "PA", indicativo: "+507", nombre: "Panamá" },
    { codigo: "BO", indicativo: "+591", nombre: "Bolivia" },
    { codigo: "UY", indicativo: "+598", nombre: "Uruguay" },
    { codigo: "JM", indicativo: "+1", nombre: "Jamaica" },
    { codigo: "TT", indicativo: "+1", nombre: "Trinidad y Tobago" },
    { codigo: "BZ", indicativo: "+501", nombre: "Belice" },
    { codigo: "GY", indicativo: "+592", nombre: "Guyana" },
    { codigo: "SR", indicativo: "+597", nombre: "Surinam" },
    { codigo: "BB", indicativo: "+1", nombre: "Barbados" },
    { codigo: "LC", indicativo: "+1", nombre: "Santa Lucía" },
    { codigo: "KN", indicativo: "+1", nombre: "San Cristóbal y Nieves" },
    { codigo: "VC", indicativo: "+1", nombre: "San Vicente y las Granadinas" },
    
    // Europa
    { codigo: "ES", indicativo: "+34", nombre: "España" },
    { codigo: "FR", indicativo: "+33", nombre: "Francia" },
    { codigo: "DE", indicativo: "+49", nombre: "Alemania" },
    { codigo: "IT", indicativo: "+39", nombre: "Italia" },
    { codigo: "GB", indicativo: "+44", nombre: "Reino Unido" },
    { codigo: "PT", indicativo: "+351", nombre: "Portugal" },
    { codigo: "RU", indicativo: "+7", nombre: "Rusia" },
    { codigo: "NL", indicativo: "+31", nombre: "Países Bajos" },
    { codigo: "BE", indicativo: "+32", nombre: "Bélgica" },
    { codigo: "SE", indicativo: "+46", nombre: "Suecia" },
    { codigo: "PL", indicativo: "+48", nombre: "Polonia" },
    { codigo: "GR", indicativo: "+30", nombre: "Grecia" },
    { codigo: "DK", indicativo: "+45", nombre: "Dinamarca" },
    { codigo: "FI", indicativo: "+358", nombre: "Finlandia" },
    { codigo: "NO", indicativo: "+47", nombre: "Noruega" },
    { codigo: "AT", indicativo: "+43", nombre: "Austria" },
    { codigo: "CH", indicativo: "+41", nombre: "Suiza" },
    { codigo: "CZ", indicativo: "+420", nombre: "República Checa" },
    { codigo: "HU", indicativo: "+36", nombre: "Hungría" },
    { codigo: "RO", indicativo: "+40", nombre: "Rumanía" },
    { codigo: "BG", indicativo: "+359", nombre: "Bulgaria" },
    { codigo: "HR", indicativo: "+385", nombre: "Croacia" },
    { codigo: "SI", indicativo: "+386", nombre: "Eslovenia" },
    { codigo: "SK", indicativo: "+421", nombre: "Eslovaquia" },
    { codigo: "IS", indicativo: "+354", nombre: "Islandia" },
    { codigo: "LI", indicativo: "+423", nombre: "Liechtenstein" },
    { codigo: "MT", indicativo: "+356", nombre: "Malta" },
    { codigo: "AL", indicativo: "+355", nombre: "Albania" },
    { codigo: "MD", indicativo: "+373", nombre: "Moldavia" },
    { codigo: "UA", indicativo: "+380", nombre: "Ucrania" },
    { codigo: "BY", indicativo: "+375", nombre: "Bielorrusia" },
    { codigo: "KZ", indicativo: "+7", nombre: "Kazajistán" },
];

export default codigosPaises;
